name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Xcode project
      run: |
        xcodebuild \
          -project NepaliPatro.xcodeproj \
          -scheme NepaliPatro \
          -sdk macosx \
          -configuration Debug \
          clean build

    - name: Run Tests
      run: |
        xcodebuild \
          -project NepaliPatro.xcodeproj \
          -scheme NepaliPatro \
          -sdk macosx \
          -configuration Debug \
          -destination 'platform=macOS' \
          test
